---

- name: FUN development stack
  hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    edxapp_root: "/edx/app"
    edxapp_home: "{{ edxapp_root }}/edxapp"
    virtualenv: "{{ edxapp_home }}/venvs/edxapp"
    edx_ansible_venv: "{{ edxapp_root }}/edx_ansible/venvs/edx_ansible"
    python: "{{ virtualenv }}/bin/python"
    mount_base: "{{ lookup('env', 'VAGRANT_MOUNT_BASE') }}"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Uninstall google-chrome
      apt: name=google-chrome-stable state=absent
    - name: Uninstall firefox
      apt: name=firefox state=absent
    - name: Uninstall myssql 5.6
      apt: name=mysql-server-5.6 state=absent purge=yes
    - name: Install myssql-common (5.5)
      apt: name=mysql-common=5.5.41-0ubuntu0.12.04.1 state=present
    - name: Install mysql-client-5.5
      apt: name=mysql-client-5.5 state=present
    - name: Make sure no flag file prevents mysql-5.5 install
      file: path=/var/lib/mysql/debian-5.6.flag state=absent

    - debug: var=mount_base
    - name: Create fun-apps folder
      file: state=directory path={{ edxapp_home }}/fun-apps/ owner=edxapp group=edxapp
      when: mount_base == ""
    - name: Create edx-platform folder
      file: state=directory path={{ edxapp_home }}/edx-platform/ owner=edxapp group=edxapp
      when: mount_base == ""
    - name: Create themes/fun folder
      file: state=directory path={{ edxapp_home }}/themes/fun/ owner=edxapp group=edxapp
      when: mount_base == ""
    - name: Create cs_comments_service folder
      file: state=directory path={{ edxapp_root }}/forum/cs_comments_service/ owner=forum group=forum

    - name: Checkout fun-apps code
      git: repo=https://github.com/openfun/fun-apps dest={{ edxapp_home }}/fun-apps/ version={{ fun_release }}
      sudo_user: edxapp
      when: mount_base == ""
    - name: Checkout themes/fun code
      git: repo=https://github.com/openfun/edx-theme dest={{ edxapp_home }}/themes/fun version={{ fun_release }}
      sudo_user: edxapp
      when: mount_base == ""
    - name: Checkout edx-platform code
      git: repo=https://github.com/openfun/edx-platform dest={{ edxapp_home }}/edx-platform/ version={{ openedx_fun_release }}
      sudo_user: edxapp
      when: mount_base == ""

    - name: Create test report folder
      file: state=directory path={{ edxapp_home }}/edx-platform/reports/
      sudo_user: edxapp
    - name: Create test report lms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/reports/lms
      sudo_user: edxapp
    - name: Create test report cms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/reports/cms
      sudo_user: edxapp
    - name: Create .testids folder
      file: state=directory path={{ edxapp_home }}/edx-platform/.testids/
      sudo_user: edxapp
    - name: Create .testids lms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/.testids/lms
      sudo_user: edxapp
    - name: Create .testids cms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/.testids/cms
      sudo_user: edxapp
    - name: Create attestations folder
      file: state=directory path=/edx/var/edxapp/attestations/
      sudo_user: edxapp

    - name: Fix venv permissions
      file:
        path={{ edx_ansible_venv }}
        state=directory
        recurse=yes owner=edx-ansible group=edx-ansible
    - name: Install old distribute
      pip: virtualenv={{ virtualenv }} name=distribute state=present version=0.6.4
      sudo_user: edxapp

    - debug: msg="Running Edx ansible scripts for release {{ openedx_release }} (FUN release {{ openedx_fun_release }})"
      tags:
          - edx-devstack
    - name: Run vagrant-devstack.yml playbook from Edx
      shell: . /edx/app/edx_ansible/venvs/edx_ansible/bin/activate &&
          ansible-playbook -i localhost, -c local vagrant-devstack.yml
          -e configuration_version={{ openedx_release }}
          -e edx_platform_version={{ openedx_fun_release }}
          -e certs_version={{ openedx_release }}
          -e forum_version={{ openedx_release }}
          -e xqueue_version={{ openedx_release }}
        chdir="/edx/app/edx_ansible/edx_ansible/playbooks"
      tags:
          - edx

    - name: Install setuptools
      pip: virtualenv={{ virtualenv }} name=setuptools state=latest
      sudo_user: edxapp
    - name: Upgrate setuptools (yes, AGAIN)
      pip: virtualenv={{ virtualenv }} name=setuptools state=latest
      sudo_user: edxapp
    - name: Install fun-apps base requirements
      pip: virtualenv={{ virtualenv }} requirements="{{ edxapp_home }}/fun-apps/requirements/base.txt"
      sudo_user: edxapp
    - name: Install fun-apps dm-xblock requirements
      pip: virtualenv={{ virtualenv }} requirements="{{ edxapp_home }}/fun-apps/requirements/dm-xblock.txt"
      sudo_user: edxapp
    - name: Install fun-apps dev requirements
      pip: virtualenv={{ virtualenv }} requirements="{{ edxapp_home }}/fun-apps/requirements/dev.txt"
      sudo_user: edxapp

    - name: Ensure lms.env.json config uses a custom theme
      lineinfile:
        'dest={{ edxapp_home }}/lms.env.json
        backrefs=yes
        regexp="( +\"USE_CUSTOM_THEME\": )false(.*)"
        line="\1true\2"'
      sudo_user: edxapp
    - name: Ensure lms.env.json config uses the fun theme
      lineinfile:
        'dest={{ edxapp_home }}/lms.env.json
        backrefs=yes
        regexp="( +\"THEME_NAME\": )\"\"(.*)"
        line="\1\"fun\"\2"'
      sudo_user: edxapp

    - name: Ensure cms.env.json config uses a custom theme
      lineinfile:
        'dest={{ edxapp_home }}/cms.env.json
        backrefs=yes
        regexp="( +\"USE_CUSTOM_THEME\": )false(.*)"
        line="\1true\2"'
      sudo_user: edxapp
    - name: Ensure cms.env.json config uses the fun theme
      lineinfile:
        'dest={{ edxapp_home }}/cms.env.json
        backrefs=yes
        regexp="( +\"THEME_NAME\": )\"\"(.*)"
        line="\1\"fun\"\2"'
      sudo_user: edxapp

    - name: Syncdb for lms
      shell: "{{ virtualenv }}/bin/fun lms.dev syncdb"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp
    - name: Syncdb for cms
      shell: "{{ virtualenv }}/bin/fun cms.dev syncdb"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp
    - name: Migrate lms
      shell: "{{ virtualenv }}/bin/fun lms.dev migrate"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp
    - name: Migrate cms
      shell: "{{ virtualenv }}/bin/fun cms.dev migrate"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp
